apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: myapp
    tier: front-end
spec:
  containers:
  - name: nginx-controller
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "250m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
